### ISSUE TITLE
[BUG] Key/Value pairs in groups are stored as a list which is annoying to iterate through with jinja2 templating

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/cloud-init#31]
meta-data is currently structured as a list of key/value pairs:
```yaml
groups:
  x1000:
  - syslog_aggregator: 127.0.0.2
```

This proposes a change which would look like this:
```yaml
groups:
  x1000:
    syslog_aggregator: 127.0.0.2
  ```
