### ISSUE TITLE
[DEV] Add standardised instance data to the cloud-init payloads

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/cloud-init#34]
The cloud-init community has agreed on a few items in the metadata that should be standard for each server implementation.

https://cloudinit.readthedocs.io/en/latest/explanation/instancedata.html#standardised-instance-data-json-v1-keys

```yaml
#cloud-config
instance-data:
  v1:
    cloud_name: ""
    availability_zone: ""
    instance_id: ""
    instance_type: ""
    local_hostname: ""
    region: ""
    hostname: ""
    plan: ""
    public_ipv4: null
    local_ipv4: null
    cloud_provider: ""
    public_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD...
    ds:
      name: ""
    vendor_data:
      version: 1.0
      features:
        - feature1
        - feature2
    metadata:
      - key: value
    attributes:
      - attribute_name: attribute_value
```
