### ISSUE TITLE
[FEATURE] Support complex datastructures in the meta-data

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/cloud-init#45]
The cloud-init server currently only supports key/value pairs represented in go as `map[string]string` in the `GroupData` struct

```go
type GroupData struct {
	Name        string            `json:"name"`
	Description string            `json:"description,omitempty"`
	Data        map[string]string `json:"meta-data,omitempty"`
	File        CloudConfigFile   `json:"file,omitempty"`
}
```

In many cases, it would be valuable to support lists, maps, and other extended structures.   I propose that we change `GroupData` such that `Data` becomes `map[string]interface{}` and update the parsing and mapping logic to support this in the code.

```go
type GroupData struct {
	Name        string            `json:"name"`
	Description string            `json:"description,omitempty"`
	Data        map[string]interface{} `json:"meta-data,omitempty"`
	File        CloudConfigFile   `json:"file,omitempty"`
}
```

**Comment by alexlovelltroy** [comment]
@travisbcotton Can you build/test this branch?  I believe it will support the list of lists that you were showing me.

**Comment by travisbcotton** [comment]
Limited testing with:
```yaml
name: test
description: "Group for all test meta-data"
meta-data:
  dict_test:
    test1:
      data: |
        bunch of stuff here
    test2:
      data: |
        newlines
        and
        stuff
  list_dicts_test:
    - name: test1
      data: stuff1
    - name: test2
      data: stuff2
  nested_test:
    - name: test1
      data:
        - entry1
        - entry2
    - name: test2
      data:
        - entry3
        - entry4
  dict_of_dicts:
    test1:
      data1:
        name: stuff1
        values:
          - v1
          - v2
      data2:
        name: stuff2
        values:
          - v3
          - v4
    test2:
      data2:
        name: blah
        different_values:
          - dv1
          - dv2
```
Not exhaustive or anything but no issues uploading this to the cloud-init groups and no issue retrieving it through the impersonation endpoint
