### ISSUE TITLE
[BUG] Returning a specific group's data with plain encoding returns list of bytes

### ISSUE THREAD

**Issue by synackd** [OpenCHAMI/cloud-init#56]
**Describe the bug**
GETting a specific group's cloud-init data via `/cloud-init/admin/groups/{group}` returns a YAML list of the integer representation of each byte in the data instead of the human-readable data itself.

**To Reproduce**
1. Start with fresh cloud-init instance.
2. Add a template and create the "compute" group:
   ```sh
   CLUSTER_BASEURI=https://foobar.openchami.cluster:8443                                           
   CLUSTER_CI_BASEURI="${CLUSTER_BASEURI}/cloud-init"
   CI_CLUSTER_KEYS=$(cat <<EOF            
   {                                          
     "name": "compute",
     "description": "ssh config templates",
     "file": {         
       "encoding": "plain",
       "content": "## template: jinja\n#cloud-config\nmerge_how:\n- name: list\n  settings: [append]\n- name: dict\n  settings: [no_replace, recurse_list]\nusers:\n  - name: root\n    ssh_authorized_keys: {{ ds.meta_data.instance_data.v1.public_keys }}\ndisable_root: false\n"
     }
   }
   EOF
   )
   curl -s -X POST -H 'Content-Type: application/json' -H "Authorization: Bearer ${ACCESS_TOKEN}" -d "${CI_CLUSTER_KEYS}"  "${CLUSTER_CI_BASEURI}/admin/groups"
   ```
3. Get config for all groups.
   ```
   curl --silent --fail "${CLUSTER_CI_BASEURI}/admin/groups"
   ```
   Output:
   ```json
   {
           "compute": {
                   "name": "compute",
                   "description": "ssh config templates",
                   "file": {
                           "content": "IyMgdGVtcGxhdGU6IGppbmphCiNjbG91ZC1jb25maWcKbWVyZ2VfaG93OgotIG5hbWU6IGxpc3QKICBzZXR0aW5nczogW2FwcGVuZF0KLSBuYW1lOiBkaWN0CiAgc2V0dGluZ3M6IFtub19yZXBsYWNlLCByZWN1cnNlX2xpc3RdCnVzZXJzOgogIC0gbmFtZTogcm9vdAogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoge3sgZHMubWV0YV9kYXRhLmluc3RhbmNlX2RhdGEudjEucHVibGljX2tleXMgfX0KZGlzYWJsZV9yb290OiBmYWxzZQo=",
                           "filename": "",
                           "encoding": "plain"
                   }
           }
   }
   ```
   Base64 decoding the content yields the correctly-formatted content:
   ```yaml
   ## template: jinja
   #cloud-config
   merge_how:
   - name: list
     settings: [append]
   - name: dict
     settings: [no_replace, recurse_list]
   users:
     - name: root
       ssh_authorized_keys: {{ ds.meta_data.instance_data.v1.public_keys }}
   disable_root: false
   ```
4. Get config for "compute" group.
   ```
   curl --silent --fail "${CLUSTER_CI_BASEURI}/admin/groups/compute"
   ```
   Output:
   ```yaml
   name: compute
   description: ssh config templates
   data: {}
   file: 
     content:
     - 35
     - 35
     - 32
     - 116
     - 101
     - 109
     - 112
     - 108
     - 97
     - 116
     - 101
     - 58
     - 32
     - 106
     - 105
     - 110
     - 106
     - 97
     - 10
     - 35
     - 99
     - 108
     - 111
     - 117
     - 100
     - 45
     - 99
     - 111
     - 110
     - 102
     - 105
     - 103
     - 10
     - 109
     - 101
     - 114
     - 103
     - 101
     - 95
     - 104
     - 111
     - 119
     - 58
     - 10
     - 45
     - 32
     - 110
     - 97
     - 109
     - 101
     - 58
     - 32
     - 108
     - 105
     - 115
     - 116
     - 10
     - 32
     - 32
     - 115
     - 101
     - 116
     - 116
     - 105
     - 110
     - 103
     - 115
     - 58
     - 32
     - 91
     - 97
     - 112
     - 112
     - 101
     - 110
     - 100
     - 93
     - 10
     - 45
     - 32
     - 110
     - 97
     - 109
     - 101
     - 58
     - 32
     - 100
     - 105
     - 99
     - 116
     - 10
     - 32
     - 32
     - 115
     - 101
     - 116
     - 116
     - 105
     - 110
     - 103
     - 115
     - 58
     - 32
     - 91
     - 110
     - 111
     - 95
     - 114
     - 101
     - 112
     - 108
     - 97
     - 99
     - 101
     - 44
     - 32
     - 114
     - 101
     - 99
     - 117
     - 114
     - 115
     - 101
     - 95
     - 108
     - 105
     - 115
     - 116
     - 93
     - 10
     - 117
     - 115
     - 101
     - 114
     - 115
     - 58
     - 10
     - 32
     - 32
     - 45
     - 32
     - 110
     - 97
     - 109
     - 101
     - 58
     - 32
     - 114
     - 111
     - 111
     - 116
     - 10
     - 32
     - 32
     - 32
     - 32
     - 115
     - 115
     - 104
     - 95
     - 97
     - 117
     - 116
     - 104
     - 111
     - 114
     - 105
     - 122
     - 101
     - 100
     - 95
     - 107
     - 101
     - 121
     - 115
     - 58
     - 32
     - 123
     - 123
     - 32
     - 100
     - 115
     - 46
     - 109
     - 101
     - 116
     - 97
     - 95
     - 100
     - 97
     - 116
     - 97
     - 46
     - 105
     - 110
     - 115
     - 116
     - 97
     - 110
     - 99
     - 101
     - 95
     - 100
     - 97
     - 116
     - 97
     - 46
     - 118
     - 49
     - 46
     - 112
     - 117
     - 98
     - 108
     - 105
     - 99
     - 95
     - 107
     - 101
     - 121
     - 115
     - 32
     - 125
     - 125
     - 10
     - 100
     - 105
     - 115
     - 97
     - 98
     - 108
     - 101
     - 95
     - 114
     - 111
     - 111
     - 116
     - 58
     - 32
     - 102
     - 97
     - 108
     - 115
     - 101
     - 10
     name: ""
     encoding: plain
   ```

**Expected behavior**
The output of Step 4 should be the base64-decoded contents of the `content` of Step 3, or be the base64-encoded string with `encoding` set to `base64`.
