### ISSUE TITLE
[BUG] Impersonating non-existent node does not err

### ISSUE THREAD

**Issue by synackd** [OpenCHAMI/cloud-init#67]
**Describe the bug**
_Scenario 1:_ Querying `/cloud-init/admin/impersonation/<n>/<m>` for nonexistent node `<n>` and where `<m>` id `meta-data`, `vendor-data`, or `user-data` does not err and instead returns data.

_Scenario 2:_ However, when querying `/cloud-init/admin/impersonation/<n>/{group}.yaml` where `{group}` is an existing group, an error does occur; however the error is "Group not found" instead of an error indicating that the node was not found.

**To Reproduce**
Steps to reproduce the behavior for _Scenario 1_:
1. Start with clean cloud-init
2. Try and get meta-data for non-existent node, e.b. `b`
   ```
   curl https://foobar.openchami.cluster:8443/cloud-init/admin/impersonation/b/meta-data
   ```
   Result:
   ```yaml
   instance-id: i-e62d3be6
   local-hostname: de0000
   hostname: de0000
   cluster-name: demo
   instance_data:
     v1:
       instance_id: i-e62d3be6
       local_ipv4: ""
       vendor_data:
         version: "1.0"
         cluster_name: demo
         groups: {}
   ```

Steps to reproduce the behavior for _Scenario 2_:
1. Start with clean cloud-init and SMD with node `x3000c0s0b0n0` in group `compute`.
2. Add a `compute` group to cloud-init.
   ```
   curl -X POST https://demo.openchami.cluster:8443/cloud-init/admin/groups -d '{"description":"compute group","name":"compute","file":{"content":"#cloud-config","encoding":"plain"}}'
   ```
3. `curl https://redondo.usrc:8443/cloud-init/admin/impersonation/b/compute.yaml`
   ```
   Group not found
   ```
4. `curl https://redondo.usrc:8443/cloud-init/admin/impersonation/x3000c0s0b0n0/compute.yaml`
   ```
   ## template: jinja
   #cloud-config
   merge_how:
   - name: list
     settings: [append]
   - name: dict
     settings: [no_replace, recurse_list]
   users:
     - name: root
       ssh_authorized_keys: {{ ds.meta_data.instance_data.v1.public_keys }}
   disable_root: false
   ```

**Expected behavior**
404 Not Found error to be returned with indication that node doesn't exist.

**Additional context**
cloud-init v1.1.1
