### ISSUE TITLE
[BUG] cloud-config returned as base64 when stored as base64

### ISSUE THREAD

**Issue by synackd** [OpenCHAMI/cloud-init#72]
**Describe the bug**
If a cloud-config is base64-encoded when storing for a group, it is returned as base64-encoded when sending a GET to:

- `/cloud-init/admin/impersonation/{node}/{group}.yaml`
- `/cloud-init/{group}.yaml` for the node

with the second endpoint, this means the cloud-init client is unable to parse the cloud-config when booting.

**To Reproduce**

0. Set up SMD to have "compute" group with a node as a member, say x3000c0s0b0n0.
1. Store plaintext cloud-config:

   ```
   cat <<EOF | ochami cloud-init group set -f yaml
   ---
   - name: compute
     description: "compute group ssh config templates"
     file:
       encoding: plain
       content: |
         ## template: jinja
         #cloud-config
         merge_how:
         - name: list
           settings: [append]
         - name: dict
           settings: [no_replace, recurse_list]
         users:
           - name: root
             ssh_authorized_keys: {{ ds.meta_data.instance_data.v1.public_keys }}
         disable_root: false
   ```
2. Get plaintext cloud-config for x3000c0s0b0n0 in grou compute:

   ```
   ochami cloud-init node get group x3000c0s0b0n0 compute
   ```

   Output:

   ```yaml
   ## template: jinja
   #cloud-config
   merge_how:
   - name: list
     settings: [append]
   - name: dict
     settings: [no_replace, recurse_list]
   users:
     - name: root
       ssh_authorized_keys: {{ ds.meta_data.instance_data.v1.public_keys }}
   disable_root: false
   ```
3. Store base64-encoded cloud-config:

   ```
   cat <<EOF | ochami cloud-init group set -f yaml
   ---
   - name: compute
     description: "compute group ssh config templates"
     file:
       encoding: base64
       content: IyMgdGVtcGxhdGU6IGppbmphCiNjbG91ZC1jb25maWcKbWVyZ2VfaG93OgotIG5hbWU6IGxpc3QKICBzZXR0aW5nczogW2FwcGVuZF0KLSBuYW1lOiBkaWN0CiAgc2V0dGluZ3M6IFtub19yZXBsYWNlLCByZWN1cnNlX2xpc3RdCnVzZXJzOgogIC0gbmFtZTogcm9vdAogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoge3sgZHMubWV0YV9kYXRhLmluc3RhbmNlX2RhdGEudjEucHVibGljX2tleXMgfX0KZGlzYWJsZV9yb290OiBmYWxzZQo=
   ```
4. Get the config again:

   ```
   ochami cloud-init node get group x3000c0s0b0n0 compute
   ```

   Output:

   ```
   IyMgdGVtcGxhdGU6IGppbmphCiNjbG91ZC1jb25maWcKbWVyZ2VfaG93OgotIG5hbWU6IGxpc3QKICBzZXR0aW5nczogW2FwcGVuZF0KLSBuYW1lOiBkaWN0CiAgc2V0dGluZ3M6IFtub19yZXBsYWNlLCByZWN1cnNlX2xpc3RdCnVzZXJzOgogIC0gbmFtZTogcm9vdAogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoge3sgZHMubWV0YV9kYXRhLmluc3RhbmNlX2RhdGEudjEucHVibGljX2tleXMgfX0KZGlzYWJsZV9yb290OiBmYWxzZQo=
   ```

**Expected behavior**
Cloud-config should be plaintext when gotten, no matter if originally stored as plaintext or base64-encoded.

**Additional context**
- Cloud-Init v1.2.0
- This also occurs with `ochami cloud-init group render`
